# Generated by Django 2.2.6 on 2020-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended_hour',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='locations_attendance',
            field=models.TextField(blank=True),
        ),
    ]
