# Generated by Django 2.2.6 on 2020-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20200722_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='serivcecost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_cost', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
