# Generated by Django 2.2.6 on 2020-07-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20200724_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipmentcost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmenttpl_id', models.IntegerField(blank=True, default=0)),
                ('assigning_loc_id', models.IntegerField(blank=True, default=0)),
                ('equipment_cost', models.FloatField(blank=True, default=0)),
                ('purchased_count', models.IntegerField(blank=True, default=0)),
                ('purchased_date', models.DateField(blank=True)),
            ],
        ),
    ]
